version: '3'

services:
  mongodb:
    container_name: mongodb-got
    image: mongo:8.0.0-rc4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: got
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
