version: '3'

services:
  app:
    container_name: app-got
    image: my-express-app   # Use a imagem jรก criada
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://localhost:27017/got
    networks:
      - my-network

  mongodb:
    container_name: mongodb-got
    image: mongo:8.0.0-rc4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: got
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
    - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
